-- ============================================================
-- Hospital Management Database
-- Aggregate Function Queries
-- ============================================================

-- ============================================================
-- Q41. Count the number of patients treated by each doctor.
-- ============================================================

SELECT
    d.doctor_name,
    COUNT(a.patient_id) AS total_patients
FROM Doctors d
JOIN Appointments a
    ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_name
ORDER BY total_patients DESC;

---------------------------------------------------------------

-- ============================================================
-- Q42. Calculate the total revenue generated by each department.
-- ============================================================

SELECT
    dep.department_name,
    SUM(b.total_amount) AS total_revenue
FROM Departments dep
JOIN Doctors d
    ON dep.department_id = d.department_id
JOIN Appointments a
    ON d.doctor_id = a.doctor_id
JOIN Bills b
    ON a.appointment_id = b.appointment_id
GROUP BY dep.department_name
ORDER BY total_revenue DESC;